version: "3"

services:
  api:
    image: maven:3-adoptopenjdk-8
    container_name: math
    working_dir: /usr/app
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app